language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - echo $DB_NAME
  - mongodump --host Cluster0-shard-0/cluster0-shard-00-00-lf760.mongodb.net:27017,cluster0-shard-00-01-lf760.mongodb.net:27017,cluster0-shard-00-02-lf760.mongodb.net:27017 --ssl --username danielspeixoto --password $DB_PASS --authenticationDatabase admin --db $DB_NAME
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew test