language: java
jdk:
  - oraclejdk12

services:
  - mongodb

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

jobs:
  include:
    - stage: integration testing
      env:
        - MONGO_CONNECTION="mongodb://localhost:27017"
        - DB_NAME=test
      script:
        - ./gradlew test --tests "com.liceu.server.integration.**" --info
    - stage: system testing
      env:
        - MONGO_CONNECTION="mongodb://localhost:27017"
        - DB_NAME=test
      script:
        - ./gradlew test --tests "com.liceu.server.system.**" --info