language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull mongo
  - docker run -d -p 27017:27017 --name deffishdb mongo
  - docker ps -a
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew test