language: java
dist: xenial
jdk:
  - openjdk11

services:
  - mongodb
  - elasticsearch

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.2-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.4.2-amd64.deb && sudo service elasticsearch restart


before_script:
  - sleep 10

jobs:
  include:
    - stage: integration testing
      env:
        - MONGO_CONNECTION="mongodb://localhost:27017"
        - DB_NAME=test
        - ELASTIC_SCHEME=http
        - ELASTIC_CLUSTER=localhost
        - ELASTIC_PORT=9200
        - ELASTIC_USER=teste
        - ELASTIC_PASSWORD=teste
      script:
        - ./gradlew test --tests "com.liceu.server.integration.**" --info
    - stage: system testing
      env:
        - MONGO_CONNECTION="mongodb://localhost:27017"
        - DB_NAME=test
      script:
        - ./gradlew test --tests "com.liceu.server.system.**" --info