steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/liceu-gke-cluster/kotlinserver', '.']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/liceu-gke-cluster/kotlinserver']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f' ,'/kubernetes/deployment.yaml']  # -> for updates in case of addition of new rule in yaml or new configMap variable/secret
#  - name: 'gcr.io/cloud-builders/kubectl'
#    args: ['set', 'image', 'deployment/liceu-main', 'my-container=gcr.io/liceu-main/kotlinserver'] # -> for updates in image or resource
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=liceu-test-cluster'