steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/liceu-gke-cluster/kotlinserver', '.']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/liceu-gke-cluster/kotlinserver']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f' ,'kubernetes/dev/service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=liceu-test-cluster'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f' ,'kubernetes/dev/deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=liceu-test-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f' ,'kubernetes/prod/service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=liceu-test-cluster'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f' ,'kubernetes/prod/deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=liceu-test-cluster'