steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/liceu-main/kotlinServer', '.']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/liceu-main/kotlinServer']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment.yaml', 'my-container=gcr.io/liceu-main/kotlinServer']