server:
  port : ${PORT}

auth:
  secret: ${AUTH_SECRET}
  prefix: ${AUTH_PREFIX}

google:
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT_SECRET}
  imageBucket: ${GOOGLE_IMAGE_BUCKET}
  documentBucket: ${GOOGLE_DOCUMENT_BUCKET}

slack:
  slackReportWebhook: ${SLACK_REPORT_WEBHOOK}

client:
  api_key: ${API_KEY}

mongo:
  dbName: ${MONGO_DB_NAME}
  uri: ${MONGO_CONNECTION}

firebase:
  cloudMessaging: ${FIREBASE_CLOUD_MESSAGING_SERVER_KEY}

elasticsearch:
  elasticCluster: ${ELASTIC_CLUSTER}
  elasticUser: ${ELASTIC_USER}
  elasticPassword: ${ELASTIC_PASSWORD}
  elasticPort: ${ELASTIC_PORT}
  elasticScheme: ${ELASTIC_SCHEME}

spring:
  mvc.favicon.enabled: false
  main:
    banner-mode: "off"

endpoints.health.sensitive : false
management.endpoint.health.show-details: always

management.health.elasticsearch.enabled: false

values:
  triviaAmount: ${TRIVIA_AMOUNT}
  challengeHistoryAmount: ${CHALLENGE_HISTORY_AMOUNT}
  postsNumberApproval: ${POSTS_NUMBER_APPROVAL}
  reportTagsAmount: ${REPORT_TAGS_AMOUNT}
  reportParamsAmount: ${REPORT_PARAMS_AMOUNT}
  reportMessageLength: ${REPORT_MESSAGE_LENGTH}
  postFinderAmount: ${POST_FINDER_AMOUNT}
  postSavedAmount: ${POST_SAVED_AMOUNT}
