server:
  port : ${PORT}

auth:
  secret: ${AUTH_SECRET}
  prefix: ${AUTH_PREFIX}

google:
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT_SECRET}
  imageBucket: ${GOOGLE_IMAGE_BUCKET}

client:
  api_key: ${API_KEY}

mongo:
  dbName: ${MONGO_DB_NAME}
  uri: ${MONGO_CONNECTION}

spring:
  mvc.favicon.enabled: false
  main:
    banner-mode: "off"