server:
  port : ${PORT}

auth:
  secret: ${AUTH_SECRET}
  prefix: ${AUTH_PREFIX}

google:
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT_SECRET}
  imageBucket: ${GOOGLE_IMAGE_BUCKET}
  documentBucket: ${GOOGLE_DOCUMENT_BUCKET}

slack:
  slackReportWebhook: ${SLACK_REPORT_WEBHOOK}

client:
  api_key: ${API_KEY}

mongo:
  dbName: ${MONGO_DB_NAME}
  uri: ${MONGO_CONNECTION}

firebase:
  cloudMessaging: ${FIREBASE_CLOUD_MESSAGING_SERVER_KEY}

spring:
  mvc.favicon.enabled: false
  main:
    banner-mode: "off"

values:
  triviaAmount: ${TRIVIA_AMOUNT}
  challengeHistoryAmount: ${CHALLENGE_HISTORY_AMOUNT}
  postsNumberApproval: ${POSTS_NUMBER_APPROVAL}
