server:
  port : ${PORT}

auth:
  secret: ${AUTH_SECRET}
  prefix: ${AUTH_PREFIX}

client:
  api_key: ${API_KEY}

mongo:
  dbName: ${MONGO_DB_NAME}
  uri: ${MONGO_CONNECTION}

spring.mvc.favicon.enabled: false
